---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: {{ .Values.devworkspace.name }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  routingClass: che
  started: true
  contributions:
  - name: ide
    uri: {{ .Values.devworkspace.devfile }}
  template:
    projects:
    - name: {{ .Values.devworkspace.name }}
      git:
        remotes:
          origin: {{ .Values.devworkspace.projects.repoUrl }}
        checkoutFrom:
          revision: {{ .Values.devworkspace.projects.revision }}
    components:
    {{- toYaml .Values.devworkspace.components | nindent 4 }}
