---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: llama-stack-k8s-operator
    control-plane: controller-manager
  name: llama-stack-k8s-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: llama-stack-k8s-operator
    control-plane: controller-manager
