---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: placeholder  # This will be ignored by Kustomize when patching
spec:
  resourceHealthChecks:
  - group: serving.kserve.io
    kind: InferenceService
    check: |
      hs = {}
      if obj.status ~= nil then
        if obj.status.modelStatus ~= nil then
          if obj.status.modelStatus.transitionStatus == "UpToDate" then
            hs.status = "Healthy"
            hs.message = obj.status.url
          else
            hs.status = "Progressing"
            hs.message = obj.status.modelStatus.transitionStatus
          end
          return hs
        end
      end
      hs.status = "Degraded"
      hs.message = "Not at latest version, no known status"
      return hs
