apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: ocp-mcp-server
  labels:
    app: ocp-mcp-server
spec:
  selector:
    app: ocp-mcp-server
    deployment: ocp-mcp-server
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
